### ISSUE TITLE
Can not build on Windows11 - tag v0.8.0

### ISSUE THREAD

**Issue by daijh** [google-ai-edge/LiteRT-LM#1032]
## Build

```shell
git checkout v0.8.0

bazelisk build --config=linux --define=litert_link_capi_so=true --define=resolve_symbols_in_exec=false //runtime/engine:litert_lm_main
```

**The same command builds successfully on Linux.**

## Log

```text
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\bin\HostX64\x64\link.exe @bazel-out/x64_windows-opt/bin/runtime/engine/litert_lm_main.exe-2.params
# Configuration: caa3fa55ee4af2cd12bcf3a2644144d52f7cc431752159138ce45c220c88c538
# Execution platform: @@local_execution_config_platform//:platform
   Creating library bazel-out\x64_windows-opt\bin\runtime\engine\litert_lm_main.lib and object bazel-out\x64_windows-opt\bin\runtime\engine\litert_lm_main.exp
llm_litert_compiled_model_executor.lib(llm_litert_compiled_model_executor.obj) : error LNK2019: unresolved external symbol LiteRtCompiledModelResizeInputTensor referenced in function "public: class litert::Expected<void> __cdecl litert::CompiledModel::ResizeInputTensor(unsigned __int64,unsigned __int64,class absl::lts_20250814::Span<int const >)" (?ResizeInputTensor@CompiledModel@litert@@QEAA?AV?$Expected@X@2@_K0V?$Span@$$CBH@lts_20250814@absl@@@Z)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsCreate referenced in function "public: static class litert::Expected<class litert::google_tensor::GoogleTensorOptions> __cdecl litert::google_tensor::GoogleTensorOptions::Create(void)" (?Create@GoogleTensorOptions@google_tensor@litert@@SA?AV?$Expected@VGoogleTensorOptions@google_tensor@litert@@@3@XZ)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsGetIdentifier referenced in function "public: static class litert::Expected<class litert::google_tensor::GoogleTensorOptions> __cdecl litert::google_tensor::GoogleTensorOptions::Create(class litert::OpaqueOptions &)" (?Create@GoogleTensorOptions@google_tensor@litert@@SA?AV?$Expected@VGoogleTensorOptions@google_tensor@litert@@@3@AEAVOpaqueOptions@3@@Z)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsGet referenced in function "private: class LiteRtGoogleTensorOptionsT * __cdecl litert::google_tensor::GoogleTensorOptions::Data(void)const " (?Data@GoogleTensorOptions@google_tensor@litert@@AEBAPEAVLiteRtGoogleTensorOptionsT@@XZ)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsSetFloatTruncationType referenced in function "public: void __cdecl litert::google_tensor::GoogleTensorOptions::SetFloatTruncationType(enum LiteRtGoogleTensorOptionsTruncationType)" (?SetFloatTruncationType@GoogleTensorOptions@google_tensor@litert@@QEAAXW4LiteRtGoogleTensorOptionsTruncationType@@@Z)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsGetFloatTruncationType referenced in function "public: enum LiteRtGoogleTensorOptionsTruncationType __cdecl litert::google_tensor::GoogleTensorOptions::GetFloatTruncationType(void)const " (?GetFloatTruncationType@GoogleTensorOptions@google_tensor@litert@@QEBA?AW4LiteRtGoogleTensorOptionsTruncationType@@XZ)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsSetInt64ToInt32Truncation referenced in function "public: void __cdecl litert::google_tensor::GoogleTensorOptions::SetInt64ToInt32Truncation(bool)" (?SetInt64ToInt32Truncation@GoogleTensorOptions@google_tensor@litert@@QEAAX_N@Z)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsGetInt64ToInt32Truncation referenced in function "public: bool __cdecl litert::google_tensor::GoogleTensorOptions::GetInt64ToInt32Truncation(void)const " (?GetInt64ToInt32Truncation@GoogleTensorOptions@google_tensor@litert@@QEBA_NXZ)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsSetOutputDir referenced in function "public: void __cdecl litert::google_tensor::GoogleTensorOptions::SetOutputDir(class std::basic_string_view<char,struct std::char_traits<char> >)" (?SetOutputDir@GoogleTensorOptions@google_tensor@litert@@QEAAXV?$basic_string_view@DU?$char_traits@D@std@@@std@@@Z)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsGetOutputDir referenced in function "public: class std::basic_string_view<char,struct std::char_traits<char> > __cdecl litert::google_tensor::GoogleTensorOptions::GetOutputDir(void)const " (?GetOutputDir@GoogleTensorOptions@google_tensor@litert@@QEBA?AV?$basic_string_view@DU?$char_traits@D@std@@@std@@XZ)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsSetDumpOpTimings referenced in function "public: void __cdecl litert::google_tensor::GoogleTensorOptions::SetDumpOpTimings(bool)" (?SetDumpOpTimings@GoogleTensorOptions@google_tensor@litert@@QEAAX_N@Z)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsGetDumpOpTimings referenced in function "public: bool __cdecl litert::google_tensor::GoogleTensorOptions::GetDumpOpTimings(void)const " (?GetDumpOpTimings@GoogleTensorOptions@google_tensor@litert@@QEBA_NXZ)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsSetEnableLargeModelSupport referenced in function "public: void __cdecl litert::google_tensor::GoogleTensorOptions::SetEnableLargeModelSupport(bool)" (?SetEnableLargeModelSupport@GoogleTensorOptions@google_tensor@litert@@QEAAX_N@Z)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsGetEnableLargeModelSupport referenced in function "public: bool __cdecl litert::google_tensor::GoogleTensorOptions::GetEnableLargeModelSupport(void)const " (?GetEnableLargeModelSupport@GoogleTensorOptions@google_tensor@litert@@QEBA_NXZ)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsSetEnable4BitCompilation referenced in function "public: void __cdecl litert::google_tensor::GoogleTensorOptions::SetEnable4BitCompilation(bool)" (?SetEnable4BitCompilation@GoogleTensorOptions@google_tensor@litert@@QEAAX_N@Z)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsGetEnable4BitCompilation referenced in function "public: bool __cdecl litert::google_tensor::GoogleTensorOptions::GetEnable4BitCompilation(void)const " (?GetEnable4BitCompilation@GoogleTensorOptions@google_tensor@litert@@QEBA_NXZ)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsSetShardingIntensity referenced in function "public: void __cdecl litert::google_tensor::GoogleTensorOptions::SetShardingIntensity(enum LiteRtGoogleTensorOptionsShardingIntensity)" (?SetShardingIntensity@GoogleTensorOptions@google_tensor@litert@@QEAAXW4LiteRtGoogleTensorOptionsShardingIntensity@@@Z)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsGetShardingIntensity referenced in function "public: enum LiteRtGoogleTensorOptionsShardingIntensity __cdecl litert::google_tensor::GoogleTensorOptions::GetShardingIntensity(void)const " (?GetShardingIntensity@GoogleTensorOptions@google_tensor@litert@@QEBA?AW4LiteRtGoogleTensorOptionsShardingIntensity@@XZ)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsSetTestingFlags referenced in function "public: void __cdecl litert::google_tensor::GoogleTensorOptions::SetTestingFlags(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SetTestingFlags@GoogleTensorOptions@google_tensor@litert@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
litert_google_tensor_options.lib(litert_google_tensor_options.obj) : error LNK2019: unresolved external symbol LiteRtGoogleTensorOptionsGetTestingFlags referenced in function "public: class std::vector<class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > >,class std::allocator<class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > > __cdecl litert::google_tensor::GoogleTensorOptions::GetTestingFlags(void)const " (?GetTestingFlags@GoogleTensorOptions@google_tensor@litert@@QEBA?AV?$vector@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@V?$allocator@V?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@@2@@std@@XZ)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsCreate referenced in function "public: static class litert::Expected<class litert::mediatek::MediatekOptions> __cdecl litert::mediatek::MediatekOptions::Create(void)" (?Create@MediatekOptions@mediatek@litert@@SA?AV?$Expected@VMediatekOptions@mediatek@litert@@@3@XZ)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsGetIdentifier referenced in function "public: static class litert::Expected<class litert::mediatek::MediatekOptions> __cdecl litert::mediatek::MediatekOptions::Create(class litert::OpaqueOptions &)" (?Create@MediatekOptions@mediatek@litert@@SA?AV?$Expected@VMediatekOptions@mediatek@litert@@@3@AEAVOpaqueOptions@3@@Z)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsGet referenced in function "private: class LiteRtMediatekOptionsT * __cdecl litert::mediatek::MediatekOptions::Data(void)const " (?Data@MediatekOptions@mediatek@litert@@AEBAPEAVLiteRtMediatekOptionsT@@XZ)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsSetNeronSDKVersionType referenced in function "public: void __cdecl litert::mediatek::MediatekOptions::SetNeronSDKVersionType(enum LiteRtMediatekOptionsNeronSDKVersionType)" (?SetNeronSDKVersionType@MediatekOptions@mediatek@litert@@QEAAXW4LiteRtMediatekOptionsNeronSDKVersionType@@@Z)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsGetNeronSDKVersionType referenced in function "public: enum LiteRtMediatekOptionsNeronSDKVersionType __cdecl litert::mediatek::MediatekOptions::GetNeronSDKVersionType(void)" (?GetNeronSDKVersionType@MediatekOptions@mediatek@litert@@QEAA?AW4LiteRtMediatekOptionsNeronSDKVersionType@@XZ)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsSetGemmaCompilerOptimizations referenced in function "public: void __cdecl litert::mediatek::MediatekOptions::SetEnableGemmaCompilerOptimizations(bool)" (?SetEnableGemmaCompilerOptimizations@MediatekOptions@mediatek@litert@@QEAAX_N@Z)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsGetGemmaCompilerOptimizations referenced in function "public: bool __cdecl litert::mediatek::MediatekOptions::GetEnableGemmaCompilerOptimizations(void)" (?GetEnableGemmaCompilerOptimizations@MediatekOptions@mediatek@litert@@QEAA_NXZ)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsSetPerformanceMode referenced in function "public: void __cdecl litert::mediatek::MediatekOptions::SetPerformanceMode(enum LiteRtMediatekNeuronAdapterPerformanceMode)" (?SetPerformanceMode@MediatekOptions@mediatek@litert@@QEAAXW4LiteRtMediatekNeuronAdapterPerformanceMode@@@Z)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsGetPerformanceMode referenced in function "public: enum LiteRtMediatekNeuronAdapterPerformanceMode __cdecl litert::mediatek::MediatekOptions::GetPerformanceMode(void)" (?GetPerformanceMode@MediatekOptions@mediatek@litert@@QEAA?AW4LiteRtMediatekNeuronAdapterPerformanceMode@@XZ)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsSetL1CacheOptimizations referenced in function "public: void __cdecl litert::mediatek::MediatekOptions::SetEnableL1CacheOptimizations(bool)" (?SetEnableL1CacheOptimizations@MediatekOptions@mediatek@litert@@QEAAX_N@Z)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsGetL1CacheOptimizations referenced in function "public: bool __cdecl litert::mediatek::MediatekOptions::GetEnableL1CacheOptimizations(void)" (?GetEnableL1CacheOptimizations@MediatekOptions@mediatek@litert@@QEAA_NXZ)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsSetOptimizationHint referenced in function "public: void __cdecl litert::mediatek::MediatekOptions::SetOptimizationHint(enum LiteRtMediatekNeuronAdapterOptimizationHint)" (?SetOptimizationHint@MediatekOptions@mediatek@litert@@QEAAXW4LiteRtMediatekNeuronAdapterOptimizationHint@@@Z)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsGetOptimizationHint referenced in function "public: enum LiteRtMediatekNeuronAdapterOptimizationHint __cdecl litert::mediatek::MediatekOptions::GetOptimizationHint(void)" (?GetOptimizationHint@MediatekOptions@mediatek@litert@@QEAA?AW4LiteRtMediatekNeuronAdapterOptimizationHint@@XZ)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsSetDisableDlaDirRemoval referenced in function "public: void __cdecl litert::mediatek::MediatekOptions::SetDisableDlaDirRemoval(bool)" (?SetDisableDlaDirRemoval@MediatekOptions@mediatek@litert@@QEAAX_N@Z)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsGetDisableDlaDirRemoval referenced in function "public: bool __cdecl litert::mediatek::MediatekOptions::GetDisableDlaDirRemoval(void)" (?GetDisableDlaDirRemoval@MediatekOptions@mediatek@litert@@QEAA_NXZ)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsSetMediatekDlaDir referenced in function "public: void __cdecl litert::mediatek::MediatekOptions::SetMediatekDlaDir(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SetMediatekDlaDir@MediatekOptions@mediatek@litert@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
litert_mediatek_options.lib(litert_mediatek_options.obj) : error LNK2019: unresolved external symbol LiteRtMediatekOptionsGetMediatekDlaDir referenced in function "public: class std::basic_string_view<char,struct std::char_traits<char> > __cdecl litert::mediatek::MediatekOptions::GetMediatekDlaDir(void)" (?GetMediatekDlaDir@MediatekOptions@mediatek@litert@@QEAA?AV?$basic_string_view@DU?$char_traits@D@std@@@std@@XZ)
bazel-out\x64_windows-opt\bin\runtime\engine\litert_lm_main.exe : fatal error LNK1120: 37 unresolved externals
Target //runtime/engine:litert_lm_main failed to build
INFO: Elapsed time: 41.576s, Critical Path: 1.67s
INFO: 2 processes: 2 internal.
ERROR: Build did NOT complete successfully
```
